In [1]:
import numpy as np

In [4]:
arr1 = np.ndarray(shape=(2, 2), dtype=float, order='F')

In [6]:
arr1[0,0] = 1

In [7]:
arr1

array([[1.00000000e+000, 1.64029794e-321],
       [1.12465777e-311, 3.79442416e-321]])

In [1]:
import torch

torch.cuda.is_available()

False

In [6]:
torch.device("cpu")

device(type='cpu')

In [2]:
import torch

In [5]:
GRU = torch.nn.GRU(6, 10, 3) # input_size, hidden_size, num_layers 
input_data = torch.randn(5, 3, 6)
h0 = torch.randn(3, 3, 10) #h0 is the initial hidden state of the GRU, which is a tensor of shape (num_layers * num_directions, batch, hidden_size)
#batch is the number of samples in a batch, hidden_size is the number of hidden units in the GRU cell, and num_layers is the number of layers in the GRU cell.
output, hn = GRU(input_data, h0)

print(output.size(), hn.size())
print(GRU)#GRU(6, 10, num_layers=2) means that the input size is 6, the hidden size is 10, and the number of layers is 2.

torch.Size([5, 3, 10]) torch.Size([3, 3, 10])
GRU(6, 10, num_layers=3)


torchsummary is used to print the model summary -> model must be object of nn.Module class

In [5]:
from torchvision import models
from torchsummary import summary

In [35]:
'''
Author: hibana2077 hibana2077@gmail.com
Date: 2022-12-25 13:20:07
LastEditors: hibana2077 hibana2077@gmail.com
LastEditTime: 2022-12-28 00:17:46
FilePath: \OOP-independent-study\lab\lab.ipynb
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
'''
#test linear model


class simple_liner_reg(torch.nn.Module):
    def __init__(self):
        super(simple_liner_reg, self).__init__()
        self.linear = torch.nn.Linear(10, 1)

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

model = simple_liner_reg()
summary(model, (10, 10))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 10, 1]              11
Total params: 11
Trainable params: 11
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


# Note

惹果使用summary函數 要把input shape 跟模型的 input shape 一樣

In [3]:
class more_complex_liner_model(torch.nn.Module):
    def __init__(self):
        super(more_complex_liner_model, self).__init__()
        self.linear1 = torch.nn.Linear(1, 10)
        self.linear2 = torch.nn.ReLU()
        self.linear3 = torch.nn.Linear(10, 256)
        self.linear4 = torch.nn.Sigmoid()
        self.linear5 = torch.nn.Linear(256, 1)

    def forward(self, x):
        y_pred = self.linear1(x)
        y_pred = self.linear2(y_pred)
        y_pred = self.linear3(y_pred)
        y_pred = self.linear4(y_pred)
        y_pred = self.linear5(y_pred)
        return y_pred



In [8]:
sumodel = more_complex_liner_model()
summary(sumodel, (1, 1))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 1, 10]              20
              ReLU-2                [-1, 1, 10]               0
            Linear-3               [-1, 1, 256]           2,816
           Sigmoid-4               [-1, 1, 256]               0
            Linear-5                 [-1, 1, 1]             257
Total params: 3,093
Trainable params: 3,093
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.01
Estimated Total Size (MB): 0.02
----------------------------------------------------------------


In [23]:
problem = lambda x: x**2 + 2*x + 1
x = torch.randn(50,1) #-> toech.randn(100,1)
y = problem(x)


In [24]:
y

tensor([[1.8155e+00],
        [2.4277e+00],
        [1.9643e+00],
        [1.1481e+00],
        [3.9353e-01],
        [1.2235e+00],
        [1.2990e-01],
        [1.1840e+01],
        [3.0310e+00],
        [8.1342e-01],
        [9.8664e-01],
        [3.4312e+00],
        [1.7889e-01],
        [9.1552e-01],
        [1.0333e-02],
        [4.8984e-03],
        [1.6847e+00],
        [1.7565e+00],
        [9.2487e+00],
        [2.1738e+00],
        [1.2422e+00],
        [1.8460e+00],
        [3.2459e+00],
        [1.9718e-01],
        [5.0153e+00],
        [5.1898e-01],
        [3.2166e-01],
        [2.0772e-01],
        [2.3889e+00],
        [3.5979e-01],
        [5.0834e-01],
        [9.9453e-02],
        [7.5945e+00],
        [1.2192e-03],
        [9.9511e-01],
        [1.2235e+00],
        [2.4339e-02],
        [1.5950e+00],
        [4.5948e+00],
        [3.6255e+00],
        [2.2705e-01],
        [2.0500e+00],
        [3.7611e+00],
        [4.9926e+00],
        [8.8415e-01],
        [1

In [25]:
x

tensor([[ 0.3474],
        [ 0.5581],
        [ 0.4015],
        [ 0.0715],
        [-0.3727],
        [ 0.1061],
        [-0.6396],
        [ 2.4409],
        [ 0.7410],
        [-0.0981],
        [-0.0067],
        [ 0.8523],
        [-0.5771],
        [-0.0432],
        [-0.8984],
        [-0.9300],
        [ 0.2980],
        [ 0.3253],
        [ 2.0412],
        [ 0.4744],
        [ 0.1145],
        [ 0.3587],
        [ 0.8016],
        [-0.5559],
        [ 1.2395],
        [-0.2796],
        [-1.5672],
        [-0.5442],
        [ 0.5456],
        [-0.4002],
        [-0.2870],
        [-0.6846],
        [ 1.7558],
        [-0.9651],
        [-0.0024],
        [ 0.1061],
        [-0.8440],
        [ 0.2629],
        [ 1.1436],
        [ 0.9041],
        [-0.5235],
        [ 0.4318],
        [ 0.9394],
        [ 1.2344],
        [-0.0597],
        [-0.9682],
        [-0.9850],
        [ 0.3211],
        [ 1.0814],
        [ 0.6482]])

In [26]:
def train_model(model, loss_fn, optimizer, x, y, epochs=100000):
    for epoch in range(epochs):
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        #-----
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        #-----
        if epoch % 100 == 50:
            print(epoch, loss.item())

model = more_complex_liner_model()
loss_fn = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
train_model(model, loss_fn, optimizer, x, y)

In [28]:
print(f"f(0.3474) true: {problem(0.3474)} , f(0.3474) pred: {model(torch.tensor([0.3474])).item()}")

f(0.3474) true: 1.81548676 , f(0.3474) pred: 1.8395307064056396


In [22]:
print(f"f(6) true: {problem(6)} , f(6) pred: {model(torch.tensor([6.0])).item()}")

f(6) true: 49 , f(6) pred: 22.045780181884766


In [29]:
models.list_models()

['alexnet',
 'convnext_base',
 'convnext_large',
 'convnext_small',
 'convnext_tiny',
 'deeplabv3_mobilenet_v3_large',
 'deeplabv3_resnet101',
 'deeplabv3_resnet50',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'efficientnet_b0',
 'efficientnet_b1',
 'efficientnet_b2',
 'efficientnet_b3',
 'efficientnet_b4',
 'efficientnet_b5',
 'efficientnet_b6',
 'efficientnet_b7',
 'efficientnet_v2_l',
 'efficientnet_v2_m',
 'efficientnet_v2_s',
 'fasterrcnn_mobilenet_v3_large_320_fpn',
 'fasterrcnn_mobilenet_v3_large_fpn',
 'fasterrcnn_resnet50_fpn',
 'fasterrcnn_resnet50_fpn_v2',
 'fcn_resnet101',
 'fcn_resnet50',
 'fcos_resnet50_fpn',
 'googlenet',
 'inception_v3',
 'keypointrcnn_resnet50_fpn',
 'lraspp_mobilenet_v3_large',
 'maskrcnn_resnet50_fpn',
 'maskrcnn_resnet50_fpn_v2',
 'maxvit_t',
 'mc3_18',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet_v2',
 'mobilenet_v3_large',
 'mobilenet_v3_small',
 'mvit_v1_b',
 'mvit_v2_s',
 'quantized_googlenet',
 '

In [49]:
import numpy as np
cls_line = lambda x: 1 if x>500 else 0
cls_x = torch.tensor(np.random.randint(0,1000,(200,1)),dtype=torch.float32)
cls_y = torch.tensor([cls_line(x) for x in cls_x],dtype=torch.float32)

In [50]:
cls_x.shape

torch.Size([200, 1])

In [51]:
cls_y = cls_y.view(-1,1)
cls_y.dtype

torch.float32

In [52]:
cls_y.shape

torch.Size([200, 1])

In [42]:
class cls_model(torch.nn.Module):
    
    def __init__(self):
        super(cls_model, self).__init__()
        self.linear1 = torch.nn.Linear(1, 10)
        self.linear2 = torch.nn.ReLU()
        self.linear3 = torch.nn.Linear(10, 256)
        self.linear4 = torch.nn.Sigmoid()
        self.linear5 = torch.nn.Linear(256, 1)
        self.linear6 = torch.nn.Sigmoid()

    def forward(self, x):
        y_pred = self.linear1(x)
        y_pred = self.linear2(y_pred)
        y_pred = self.linear3(y_pred)
        y_pred = self.linear4(y_pred)
        y_pred = self.linear5(y_pred)
        y_pred = self.linear6(y_pred)
        return y_pred

In [43]:
def train_model(model, loss_fn, optimizer, x, y, epochs=100000):
    for epoch in range(epochs):
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        #-----
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        #-----
        if epoch % 100 == 50:
            print(epoch, loss.item())

In [53]:
cls_model_train = cls_model()
loss_fn = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(cls_model_train.parameters(), lr=1e-4)
train_model(cls_model_train, loss_fn, optimizer, cls_x, cls_y)

50 46.72229766845703
150 44.78269958496094
250 45.32126235961914
350 46.764949798583984
450 43.39794158935547
550 43.158180236816406
650 39.0790901184082
750 42.740333557128906
850 40.377105712890625
950 37.8568115234375
1050 39.16612243652344
1150 31.13214683532715
1250 38.10851287841797
1350 30.536846160888672
1450 24.58342742919922
1550 24.394744873046875
1650 25.378522872924805
1750 21.2594051361084
1850 19.430667877197266
1950 18.029386520385742
2050 17.121713638305664
2150 16.329452514648438
2250 15.608670234680176
2350 15.021895408630371
2450 14.49881362915039
2550 14.011905670166016
2650 13.516768455505371
2750 14.666439056396484
2850 13.715346336364746
2950 13.580373764038086
3050 13.502450942993164
3150 13.449625015258789
3250 13.395923614501953
3350 13.326910018920898
3450 13.239389419555664
3550 13.126880645751953
3650 12.998682975769043
3750 12.930997848510742
3850 12.885858535766602
3950 12.845848083496094
4050 12.80720329284668
4150 12.770545959472656
4250 12.72244071960

In [60]:
cls_model_train(torch.tensor([500.0]))

tensor([0.8306], grad_fn=<SigmoidBackward0>)