In [216]:
import torch
import torch.nn.functional as F
from torchsummary import summary
import numpy as np

In [12]:
#make random data
func = lambda x: sum(x)
x = torch.randn(1000, 10)
y = torch.tensor([func(x[i]) for i in range(len(x))])

In [13]:
x

tensor([[ 0.7640, -2.6737,  0.2391,  ...,  0.1357,  0.7859,  0.3954],
        [ 2.9059,  0.0487, -1.4335,  ...,  1.9146, -0.3864,  0.6545],
        [ 0.8722,  0.0259,  0.3161,  ..., -1.0941, -0.3016, -0.9683],
        ...,
        [ 0.0645,  1.0162,  1.1544,  ...,  1.0935,  1.6485,  0.4987],
        [-0.3103,  0.7430,  0.7674,  ...,  0.8564, -0.4231, -1.0520],
        [-0.9095, -0.2613, -0.2668,  ...,  2.7301,  2.4711, -0.1192]])

In [14]:
y = y.view(-1, 1)
y

tensor([[ 1.2202e+00],
        [ 2.6451e+00],
        [-2.2374e+00],
        [-2.0936e+00],
        [ 6.1881e-01],
        [-6.4625e-01],
        [-6.8063e-01],
        [-1.4745e+00],
        [ 5.5494e-01],
        [ 2.2392e+00],
        [-1.6048e+00],
        [ 2.6997e-01],
        [-3.0916e+00],
        [ 2.9430e-01],
        [-3.0942e+00],
        [-2.3963e+00],
        [ 1.4992e+00],
        [ 3.7417e+00],
        [ 4.3796e-01],
        [-7.7241e-01],
        [ 4.8181e+00],
        [ 7.3922e-02],
        [ 1.1605e+00],
        [ 4.0534e+00],
        [ 1.1197e+00],
        [-5.4274e+00],
        [-1.2597e+00],
        [ 3.0619e-01],
        [-3.7176e-01],
        [-4.9224e+00],
        [ 2.6760e+00],
        [-6.9033e-01],
        [ 4.1994e-01],
        [ 5.6683e+00],
        [-3.1556e+00],
        [ 2.5623e+00],
        [ 1.3466e+00],
        [-3.1690e+00],
        [-1.4144e+00],
        [-4.2573e-01],
        [-5.2465e-01],
        [-1.8641e+00],
        [ 2.2099e+00],
        [ 2

In [9]:
test_case = torch.randn(1,1,10)
test_case

tensor([[[ 1.4560, -1.4720,  1.4089, -1.7747,  2.3621, -0.7103, -0.2730,
           0.0935, -0.8061, -0.6746]]])

In [41]:
class simple_liner_reg(torch.nn.Module):
    def __init__(self):
        super(simple_liner_reg, self).__init__()
        self.linear = torch.nn.Linear(10, 1)

    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

model = simple_liner_reg()
summary(model, (10, 10))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                [-1, 10, 1]              11
Total params: 11
Trainable params: 11
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [50]:
test_case.shape

torch.Size([1, 1, 10])

In [57]:
class duo_lstm(torch.nn.Module):
    def __init__(self):
        super(duo_lstm, self).__init__()
        self.layer1 = torch.nn.LSTM(10, 15,3)
        self.h0 = torch.zeros(3, 1, 15)
        self.c0 = torch.zeros(3, 1, 15)

    def forward(self, x):
        y_pred, (h, _) = self.layer1(x, (self.h0, self.c0))
        print(h.shape)
        return y_pred

model = duo_lstm()
ans = model(test_case)
print(ans)
print(test_case.shape)

torch.Size([3, 1, 15])
tensor([[[-0.0631, -0.0127, -0.1005,  0.0687,  0.0312, -0.0278, -0.0683,
          -0.0846,  0.0310, -0.0350, -0.0279, -0.0003,  0.0574,  0.0622,
          -0.0100]]], grad_fn=<StackBackward0>)
torch.Size([1, 1, 10])


In [4]:
new_test_case = torch.randn(1, 10, 9)
new_test_case

tensor([[[ 0.8426,  0.4483, -0.4219, -0.3677, -1.6103, -0.3397, -0.1472,
          -0.5030,  0.3629],
         [-0.5383,  0.9542,  0.0420, -0.9437,  0.8620,  0.6474, -1.2915,
           1.1430,  0.8265],
         [-0.8476,  0.6108, -0.8289, -1.0679, -0.1121, -0.5100,  1.3464,
           0.0714, -0.0272],
         [-0.9716,  0.7713, -0.6602, -0.7018,  1.6961, -1.2626, -0.1119,
           0.7570, -0.2931],
         [-0.3336,  0.9621,  1.7192,  1.4697, -1.2723,  0.7179,  0.3485,
           1.6036, -0.6946],
         [-1.0510,  0.6373, -1.1711,  0.3614,  0.8133, -1.1489, -0.1655,
          -1.2136,  0.5892],
         [ 1.5342, -1.7125,  1.2294, -0.3653,  0.3367,  0.9317, -0.3221,
           0.1033, -1.4386],
         [-0.5827,  2.1962,  0.6801, -1.2514, -0.2704, -1.5490, -0.4053,
           0.4509,  0.4426],
         [-1.0195, -2.9297,  0.1169,  0.1589, -0.3357,  1.3213, -2.5882,
          -0.2516,  0.9617],
         [-1.8334,  0.1797, -1.5918,  1.1074, -0.3656,  0.4091,  1.0178,
         

In [7]:
new_test_case[0].shape

torch.Size([10, 9])

In [5]:
class SelectItem(torch.nn.Module):
    def __init__(self, item_index):
        super(SelectItem, self).__init__()
        self._name = 'selectitem'
        self.item_index = item_index

    def forward(self, inputs):
        return inputs[self.item_index]

In [8]:
#input size is (10,9)
class duo_lstm(torch.nn.Module):
    def __init__(self):
        super(duo_lstm, self).__init__()
        self.layer1 = torch.nn.LSTM(10, 15,3)
        self.h0 = torch.zeros(3, 1, 15)
        self.c0 = torch.zeros(3, 1, 15)
        self.select = SelectItem(0)

    def forward(self, x):
        y_pred, (h, _) = self.layer1(x, (self.h0, self.c0))
        print(h.shape)
        return self.select(y_pred)

In [210]:

temp = torch.randn(10,9)
temp

tensor([[ 1.3690,  0.3638, -1.0524,  0.4994,  0.7140,  1.3696,  1.9344,  0.6641,
          1.2144],
        [-1.0003, -0.7993,  0.3056, -0.7189, -0.7047, -0.8703,  0.9325, -1.5675,
         -0.5394],
        [-0.5185, -0.9057, -1.5688, -0.3268, -1.0411, -0.5398,  0.0505, -1.3925,
         -0.5908],
        [ 0.8659,  1.5290, -0.7318,  1.0998,  1.1483,  1.6535, -0.5272,  0.8173,
          1.3341],
        [-0.7663,  0.8606, -0.2731, -0.1931,  0.6275,  0.2336, -0.4570,  0.8889,
         -2.1603],
        [-0.8345, -1.1388,  0.1740,  0.0294, -0.2727, -1.2394, -0.1919, -0.3238,
         -0.6687],
        [ 2.6990, -0.2032, -1.1906,  0.5770, -1.0162,  1.2739,  0.2168,  0.3974,
          1.3368],
        [ 0.6421,  1.0311,  0.9833, -1.8008,  0.0825, -1.3736,  1.4450, -1.0868,
         -0.7678],
        [-0.0158,  0.4880,  0.3216, -0.6224, -2.4118, -1.2074, -0.6212,  1.3009,
          0.5087],
        [-0.2266, -1.2706, -0.1930, -0.3960, -1.7083, -0.9515,  0.0058,  0.7060,
         -0.3274]])

In [211]:
temp.shape

torch.Size([10, 9])

In [214]:
torch.randn(2)

tensor([-0.6058, -1.1715])

In [252]:
test_model = torch.nn.Sequential(
    torch.nn.Conv1d(10,1,1),
    torch.nn.ReLU(),
    torch.nn.LSTM(9, 12, 5),
    SelectItem(0),
    torch.nn.Linear(12, 2),
    torch.nn.Sigmoid()
)
ans = test_model(temp)
print(ans)

#summary(test_model, (10,9))



tensor([[0.5504, 0.5529]], grad_fn=<SigmoidBackward0>)


In [271]:
a_tensor = torch.randn(10,2)
a_tensor.view(10,1,2)

tensor([[[-6.3326e-01, -1.3020e+00]],

        [[-1.3800e+00, -6.5782e-01]],

        [[-7.0428e-01,  2.5372e-01]],

        [[-1.0614e+00, -1.1218e+00]],

        [[ 7.9823e-01,  7.5710e-01]],

        [[-1.2058e+00, -1.0542e+00]],

        [[ 1.4785e+00, -5.5384e-01]],

        [[-4.9727e-01, -4.7557e-01]],

        [[ 4.8486e-01,  1.0165e+00]],

        [[ 1.3686e-03, -1.0726e+00]]])

In [360]:
test_tensor = torch.randn(1,2)
print(test_tensor)
test_tensor = torch.nn.ReLU()(test_tensor)
test_tensor = torch.nn.Softmax(dim=1)(test_tensor)
print(test_tensor)

tensor([[ 0.9594, -1.2531]])
tensor([[0.7230, 0.2770]])


In [299]:
target = torch.tensor([[1.,0.]])
case_1 = torch.randn(1,2)
case_1 = torch.nn.ReLU()(case_1)
case_1

tensor([[0.3225, 0.0000]])

In [294]:
loss = torch.nn.MSELoss()
loss_func = loss(case_1,target )
print(f"{type(loss)} = {loss_func:.8f}")
loss_functional = F.mse_loss(case_1, target)
print(f"torch.nn.functional = {loss_functional.item():.8f}")

<class 'torch.nn.modules.loss.MSELoss'> = 0.80999994
torch.nn.functional = 0.80999994


- all elements of input should be between 0 and 1 -> not add sigmod to output layer

In [249]:
test_tensor = torch.tensor([100,-100])
after_sigmod = torch.sigmoid(test_tensor)
print(after_sigmod)

tensor([1., 0.])


In [17]:


class test_seq(torch.nn.Module):
    def __init__(self):
        super(test_seq, self).__init__()
        self.net = torch.nn.Sequential(
            torch.nn.Linear(10, 64),
            torch.nn.ReLU(),
            torch.nn.LSTM(64, 256, 20),# 20 layers of lstm
            SelectItem(0),
            torch.nn.GRU(256, 128, 10),# 10 layers of gru
            SelectItem(0),
            torch.nn.Linear(128, 2),
            torch.nn.Softmax(dim=1)
        )

    def forward(self, x):
        y_pred = self.net(x)
        return y_pred

model = test_seq()
out = model(torch.randn(1, 10))
out

tensor([[0.4965, 0.5035]], grad_fn=<SoftmaxBackward0>)